# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0003_auto_20161222_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioapp',
            name='app_url_text',
            field=models.CharField(default='View Application', max_length=128),
        ),
    ]
