# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0004_portfolioapp_app_url_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioapp',
            name='modal_img_url',
            field=models.URLField(blank=True),
        ),
    ]
