# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0005_portfolioapp_modal_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
    ]
